<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Load Composer's autoloader
require 'vendor/autoload.php';

if(isset($_POST['submit'])){
    // Configuration for sending emails
    $to = "gokul.dalztek@gmail.com"; // Change to your desired email address
    $first_name = $_POST['name'];
    $messageContent = $_POST['message'];
    $subject = "Form submission";
    $subject2 = "Acknowledgement from waytobank.com";

    // Email message to be sent to the admin
    $adminMessage = "Here is an Enquiry\r\n\nName: " . $first_name . "\r\n\n" . "Message: " . $messageContent;

    // Initialize PHPMailer
    $mail = new PHPMailer(true);

    try {
        //Server settings
        $mail->isSMTP();
        $mail->Host       = 'smtp.gmail.com';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'gokulrj002@gmail.com'; // Your Gmail address
        $mail->Password   = 'encf rrgn iyrp whek'; // Your Gmail password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port       = 587;

        //Recipients
        $mail->setFrom('your_email@gmail.com', 'WayToBank');
        $mail->addAddress($to);
        $mail->addReplyTo('your_email@gmail.com', 'Information');

        // Content
        $mail->isHTML(false);
        $mail->Subject = $subject;
        $mail->Body    = $adminMessage;

        // Send email to admin
        $mail->send();

        // Acknowledgment email to the user
        $userMessage = "Dear " . $first_name ."," . "\r\n\n" . "Thanks for choosing us we will contact you shortly." . "\r\n\n". "\r\n\n" . "\r\n\n" . "*This is an autogenerated mail do not reply." . "\r\n\n" . "Many Thanks," ."\r\n\n" . "Selva Kumar" . "\r\n\n" . "Director" . "\r\n\n" . "waytobank.com";

        // Send acknowledgment email to the user
        $mail->clearAddresses();
        $mail->addAddress($to);
        $mail->Subject = $subject2;
        $mail->Body    = $userMessage;

        $mail->send();

        echo "<script>alert('Mail Sent. Thank you " . $first_name . ", we will contact you shortly.');</script>";
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=false;">
    <meta name="keywords" content="Personal Loan, Credit Cards, Home Loans, Business Loans, low interest rates, Special offers, Quick Approval Loans">
    <meta name="description" content="Compare and Apply Personal Loan Online. We Offering Credit Card, Home Loan, Business Loan, Doctor Loan  at minimum rate of interest with Special offers. Call Us: +91-87 22 88 66 33 Today ">
    <meta name="robots" content="noindex">
    <!--ogp-->
    <meta property="og:title" content="Contact Us to get instant Personal Loan,quick personal loan,Apply Personal Loan, Credit Card, Home Loan, Business Loan with Special offers,instant loan,quick approvals" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.waytobank.com" />
    <meta property="og:image" content="/images/way-to-bank-logo.png" />
    <meta property="og:site_name" content="waytobank" />
    <meta property="fb:admins" content="518284204999889" />
    <meta property="og:description" content="waytobank.com a Great Platform for all Your Financial Needs You can Compare and Apply for Personal Loan, Home Loan, Credit Cards, Auto Loan the Gifted Way to You" />
    <title>Contact Us - +91-87 22 88 66 33  | www.Waytobank.com</title>
    <link rel="shortcut icon" type="image/png" href="images/favicon.png"/>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/feed.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse">
<!--navbar starts-->
<div id="nav-placeholder"></div>
<!--navbar end-->
<section class="loan-section" id="loan-section">
  <div class="container" style="margin-top: 90px;">
    <ol class="breadcrumb">
      <li><a href="\index.php" title="Home">Home</a></li>
      <li>Enquiry</li>
    </ol>
  </div>

  <div class="panel panel-default text-center">
    <h4 class="service-heading animated fadeInDown">Enquiry/Contact Form</h4>
    <p class="text-muted animated fadeInDown">Kindly provide us with some details<br> so we can line up offers most suited to you.</p>
    <div class="panel-body">
      <form class="form-horizontal row-border" name="contact" id="contactForm" novalidate="" role="form" method="post">
        <div class="col-md-12 col-sm-12">
          <div class="control-group">
            <label class="col-md-4 control-label">Full Name</label>  
            <div class="col-md-8 inputGroupContainer">
              <input name="name" id="name" placeholder="Full Name" class="form-control" type="text" required="" data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>                  
          <div class="control-group">
            <label class="col-md-4 control-label">Message</label>
            <div class="col-md-8 inputGroupContainer">
              <textarea class="form-control" name="message" id="message" placeholder="Message" required="" data-validation-required-message="Please enter your message."></textarea>
              <p class="help-block text-danger"></p>
              <div class="checkbox">
                <label><span><small class="text-danger"><b>Note:</b></small>&nbsp;By providing my contact information I authorize its representatives to call me or SMS me with reference to my loan application</span><br><span>Provided Information will be kept as Confidential.</span></label>
              </div>            
            </div>
          </div>
          <div class="control-group">              
            <div class="col-md-12" style="margin-top: 30px;"> 
              <div id="success"></div>
              <button type="submit" name="submit" class="btn btn-info" title="">Submit</button>       
            </div>
          </div>
        </div>
      </form>

     

    </div>
  </div>
</section>
<!---footer starts-->
<div id="footer-placeholder"></div>
<!---footer end-->
<!---chat start-->
<div id="chatplugin-placeholder"></div>
<!---chat end-->

<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jqBootstrapValidation.js"></script>
<script>
    $(()=>{ $("input,select,textarea").not("[type=submit]").jqBootstrapValidation(); } );
    $(()=>{ $("#nav-placeholder").load("components/navbar.html"); });
    $(()=>{ $("#footer-placeholder").load("components/footer.html");  });
    $(()=>{ $("#chatplugin-placeholder").load("components/chatplugin.html");  });
</script>
</body>
</html>
